name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  FILE_NAME_PREFIX: geoman-io-maplibre-geoman-free
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    name: release job
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          # Important so we can merge branches
          fetch-depth: 0

      - name: Set version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Check version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "${{ steps.version.outputs.version }}" != "$PACKAGE_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install just command runner
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Prepare package
        run: |
          just pack

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GEOMAN_RELEASE_TOKEN }}
          files: |
            pub/${{env.FILE_NAME_PREFIX}}-${{ steps.version.outputs.version }}.tgz
            pub/LICENSE

      - name: Publish to NPM
        shell: bash
        run: |
          #!/bin/bash

          # Set auth token
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          just publish
